 logs:
    - type: file
      path: "<RUBY_LOG_FILE_PATH>.log"
      service: ruby
      source: ruby
      sourcecategory: sourcecode
      ## Uncomment the following processing rule for multiline logs if they
      ## start by the date with the format yyyy-mm-dd
      #log_processing_rules:
      #  - type: multi_line
      #    name: new_log_start_with_date
      #    pattern: \d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])